ejercicios de Type Script y objetos
Jorge-Luques/MiJoRepositorio pull request #4
Opened 2020-07-11 01:44 UTC by Jorge-Luques

Agregue los type script de los ejercicios del arreglo global con insertar,buscar,eliminar,actualizar y ejemplos de objetos

2020-07-13 00:40 UTC, rbeltracchi requested changes
Fijate que tenes mas de un proyecto en este PR, entonces vas a necesitar acomodar el gitignore, porque te agrego un monton de archivos de node_modules proba poner el .gitignore con esto adentro:

*node_modules

El asterisco va a hacer que ignore todo lo que sea node_modules sin importar en que subcarpeta se encuentre

2020-07-13 00:40 UTC, rbeltracchi commented on POO/IntroObjetos/Auto/Automovil.ts
> +        if (this.estaPrendido){
Tendria que poder acelerar si esta prendido y ademas si tiene combustible no?

2020-07-13 23:50 UTC, Jorge-Luques commented on POO/IntroObjetos/Auto/Automovil.ts
> +        if (this.estaPrendido){
sisisi, la idea es que el automovil acelere si esta prendido y que tenga combustible para poder consumir... tenes razon! me falto la condicion de combustible

2020-08-05 14:07 UTC, rbeltracchi requested changes
Jorge acordate que trabajamos con un branch diferente por clase. No se entrega siempre en el mismo branch.

Hay que agregar node_modules a .gitignore

2020-08-05 14:07 UTC, rbeltracchi commented on POO/IntroObjetos/Auto/Automovil.ts
> +        if (this.estaPrendido){
Todavia falta la condicion de combustible aca

2020-08-06 14:21 UTC, Jorge-Luques commented
agregue mas archivos .ts, entre los cuales esta el GestorAutomotor, que lee desde archivo txt los datos de los automoviles registrados. Tambien agregue el gestor de libros

2020-08-06 17:24 UTC, rbeltracchi commented
Jorgue no sigas usando el mismo branch, tenes que hacer **un branch por clase**. Recorda eso.

Como proximos pasos tenes que agarrar todo lo que esta en este branch y dividirlo correctamente, haciendo un PR por cada clase.

2020-08-06 17:24 UTC, closed without merging